using Microsoft.AspNetCore.Mvc;
using Firebase.Database;
using Firebase.Database.Query;
using System.Dynamic;
using core;

[ApiController]
[Route("[controller]")]
public class createController : ControllerBase
{
    private readonly FirebaseClient _firebaseClient;

    public createController(FirebaseClient firebaseClient)
    {
        _firebaseClient = firebaseClient;
    }

    [HttpPost]
    public async Task<IActionResult> Create([FromBody] budget newBudget)
    {
        var result = await _firebaseClient
            .Child("budgets")
            .PostAsync(newBudget);

        if (result.Object != null)
        {
            // Construct a response object that includes the Firebase-generated ID
            var response = new
            {
                Id = result.Key, // The unique ID generated by Firebase
                Name = newBudget.Name,
                Amount = newBudget.Amount,
                Category = newBudget.Category,
                DateCreated = newBudget.DateCreated
            };

            return Ok(response);
        }
        else
        {
            return BadRequest("Could not create the budget.");
        }
    }

}